version: "3.3"
services:
  php-fpm:
    image: xcdr/php-fpm_nginx-lb_php-fpm:latest
    tty: true
    volumes:
      - ./app-files:/var/www/html
    env_file: ./app.env

  nginx-lb:
    image: xcdr/php-fpm_nginx-lb_nginx:latest
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./app-files:/var/www/html

    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "5"
