apiVersion: v1
kind: Pod
metadata:
  name: dummy-storage
spec:
  volumes:
    - name: web-app-storage
      persistentVolumeClaim:
        claimName: web-app-claim
  containers:
    - name: dummy-storage-access
      image: busybox:latest
      tty: true
      volumeMounts:
        - mountPath: "/mnt/app-data"
          name: web-app-storage
  restartPolicy: Never
