apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - name: "http-server"
      protocol: TCP
      port: 8080
      targetPort: 80
